name: Scheduled Health Check

# Controls when the action will run.
on:
  schedule:
    - cron: "*/5 * * * *"

env:
  TEAMS_WEBHOOK_RUL: ${{ secrets.TEAMS_WEBHOOK_RUL }}

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - uses: actions/checkout@v2
      - name: Run Shell Script
        id: shell_script_run
        env:
          TEAMS_WEBHOOK_RUL: ${{ secrets.TEAMS_WEBHOOK_RUL }}
        run: $TEAMS_WEBHOOK_RUL ./scripts/health-check.sh
